version: '3.5'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/database:/var/lib/mysql
  app:
    container_name: app
    build: .
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER_NAME: root
      DATABASE_PASSWORD: root
  spring:
    container_name: spring
    build: .
    volumes:
      - .:/my_app
    restart: always
    command: bundle exec spring server
    # This ensures that the pid namespace is shared between the host
    # and the container. It's not necessary to be able to run spring
    # commands, but it is necessary for "spring status" and "spring stop"
    # to work properly.
    pid: host
